# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'OC_RockeyFloral' do
 
pod 'Masonry' # 使用纯代码进行Auto Layout.
pod 'AFNetworking', '2.5.0' # 网络请求.
pod 'MJExtension' # JSON自动转为Model.
pod 'MJRefresh' # 添加上拉加载更多与下拉刷新功能.
pod 'MBProgressHUD' # 进度提示.
pod 'ReactiveCocoa' # RAC,一个支持响应式编程的库.
pod 'AFNetworking-RACExtensions' # 使AFN支持RAC模式.
pod 'Mantle' # JSON <==> Model
pod 'DateTools' # 完整的日期工具库
pod 'Objection', '1.6.1' # 依赖注入.
pod 'JSPatch' # 在线更新应用.
pod 'TTTAttributedLabel' #富文本
pod 'AMapLocation' #高德地图定位服务
pod 'BaiduMapKit' #百度地图Sdk
pod 'FMDB', '~>2.6' #数据库操作
pod 'SDWebImage' # SDWebImage
pod 'YYKit'
pod 'YLGIFImage', '~>0.11' # GIF 图片
pod 'Bugtags' # Bug追踪

end
